name: meditation
description: A new Flutter project.

version: 1.0.0+1


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_svg: ^0.18.1
  story_view:
  vector_math: ^2.0.8
  flutter_circular_chart: ^0.1.0
  simple_animations:
  curved_navigation_bar: ^0.3.1
  connectivity: ^2.0.2
  audio: ^0.0.5
  firebase_auth: ^0.18.4+1
  google_sign_in: ^4.5.6
  cloud_firestore: ^0.14.4
  global_configuration: ^1.4.0
  image_picker: ^0.6.2+2
  shimmer: ^1.0.1
  image_cropper: ^1.1.1
  firebase_storage: ^5.2.0
  #https://github.com/MaikuB/flutter_local_notifications/issues/450
  flutter_local_notifications: ^1.1.3
  intl: ^0.16.0
  shared_preferences: ^0.5.4
  firebase_messaging: ^6.0.9
  flutter_braintree: ^0.5.3
  http: ^0.12.0+4
  rflutter_alert: ^1.0.3
  share: ^0.6.3+5
  flutter_playout: ^1.0.25
  in_app_purchase: ^0.3.4
  apple_sign_in: ^0.1.0
  flutter_webview_plugin: ^0.3.11
  oauth1: ^1.0.1
  url_launcher: ^5.4.11
  firebase_core: ^0.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/img/logo-with-text.png"
  image_path_ios: "asset/img/logo-with-text-ios.png"

flutter:

  uses-material-design: true

  assets:
    - asset/img/
    - asset/img/social-icon/
    - asset/img/bg/
    - asset/config/

  fonts:
    - family: Raleway
      fonts:
        - asset: asset/font/Raleway/Raleway-Regular.ttf
          weight: 400
        - asset: asset/font/Raleway/Raleway-Medium.ttf
          weight: 500
        - asset: asset/font/Raleway/Raleway-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: asset/font/Raleway/Raleway-SemiBold.ttf
          weight: 600
        - asset: asset/font/Raleway/Raleway-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: asset/font/Raleway/Raleway-Bold.ttf
          weight: 700
        - asset: asset/font/Raleway/Raleway-BoldItalic.ttf
          weight: 700
          style: italic
module:
  androidX: true